version: '3.8'

services:
  notify-agent:
    image: server-notify-agent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4003:4003" # Expose port to localhost"
    network_mode: host # Allow the container to access the host network
    environment:
      - LOG_LEVEL=info
      - SERVICE_NAME=notify-agent
      - DATABASE_HOST=172.17.0.1
      - DATABASE_PORT=27017
      - DATABASE_NAME=notify_agent
      - DATABASE_USERNAME=golde
      - DATABASE_PASSWORD=483777